module.exports = {
  amendedHindiPerformaConciliationAssets: require("./amendedHindiPerformaConciliationAssets"),
  arbitrationPerforma: require("./arbitrationPerforma"),
  dlnPerforma: require("./dlnPerforma"),
  performa406420: require("./performa406420"),
  performaAbroadNotice: require("./performaAbroadNotice"),
  performaAbroadNoticeAssetsCasesPersonalLoan: require("./performaAbroadNoticeAssetsCasesPersonalLoan"),
  performaAssestsVerificationNoticeAvn: require("./performaAssestsVerificationNoticeAvn"),
  performaBrokenSettlementLetter: require("./performaBrokenSettlementLetter"),
  performaCivilSuitNotice: require("./performaCivilSuitNotice"),
  performaConciliation: require("./performaConciliation"),
  performaDemandNoticeAssetsCasesNew: require("./performaDemandNoticeAssetsCasesNew"),
  performaHighPetrolTransaction: require("./performaHighPetrolTransaction"),
  performaOts: require("./performaOts"),
  performaOverLimitNoticesExcessiveUseOfPetrol: require("./performaOverLimitNoticesExcessiveUseOfPetrol"),
  performaPasaMinimumDueAndMaximum: require("./performaPasaMinimumDueAndMaximum"),
  performaPasaNoticesEcsCasesAssets: require("./performaPasaNoticesEcsCasesAssets"),
  performaPdn: require("./performaPdn"),
  performaSalaryAttachmentNotice: require("./performaSalaryAttachmentNotice"),
  performaSummonsCasesOrderAttached: require("./performaSummonsCasesOrderAttached"),
  performaSummonsOrderAttachedAssetsCases: require("./performaSummonsOrderAttachedAssetsCases"),
  performaWarrantCasesOrderAttached: require("./performaWarrantCasesOrderAttached"),
  performaWarrantCasesOrderAttachedAssetsEmailPurpose: require("./performaWarrantCasesOrderAttachedAssetsEmailPurpose"),
};
