module.exports = (data) =>
  `<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Document</title>
  
      <style>
        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
          margin: 0;
          padding: 0;
          line-height: normal;
          font-weight: 700;
        }
        span {
          font-weight: 500;
          line-height: 30px;
        }
        .flex {
          display: flex;
        }
        .flex-col {
          flex-direction: column;
        }
        .items-center {
          align-items: center;
        }
        .items-end {
          align-items: end;
        }
        .justify-start {
          justify-content: left;
        }
        .justify-center {
          justify-content: center;
        }
        .justify-between {
          justify-content: space-between;
        }
        .grid {
          display: grid;
        }
        .grid-cols-3 {
          grid-template-columns: repeat(3, minmax(0, 1fr));
        }
        .w-full {
          width: 100%;
        }
        .w-50 {
          width: 50%;
        }
        .mt-5 {
          margin-top: 5px;
        }
        .bold {
          font-weight: 700;
        }
        .text-sm {
          font-size: 14px;
        }
        .block {
          display: block;
        }
        .gap-5 {
          gap: 5px;
        }
        .gap-10 {
          gap: 10px;
        }
        .underline {
          text-decoration: underline;
        }
        .leading-normal {
          line-height: normal;
        }
        .ml-10 {
          margin-left: 10px;
        }
      </style>
    </head>
    <body style="padding: 100px 90px; background-color: white">
      <div class="flex flex-col items-end">
        <h2>ARUN KUMAR</h2>
        <h3>ADVOCATE</h3>
      </div>
  
      <div class="flex justify-between">
        <div class="flex flex-col">
          <span style="line-height: 20px">Rasi: </span>
          <span style="line-height: 20px">H.No. 973, Near Shiv Mandir,</span>
          <span style="line-height: 20px">Village Gandhra</span>
          <span style="line-height: 20px">Rohtak (Haryana)</span>
          <span style="line-height: 20px">Pin Code-124001</span>
        </div>
        <div class="flex flex-col">
          <span style="line-height: 20px">Office: </span>
          <span style="line-height: 20px">Chamber No.113, District Court,</span>
          <span style="line-height: 20px">Rohtak. (Haryana)</span>
        </div>
      </div>
      <hr
        style="
          height: 2px;
          margin: 0;
          margin-top: 5px;
          padding: 0;
          border: none;
          background: black;
        "
      />
      <hr
        style="
          height: 4px;
          margin: 3px 0;
          padding: 0;
          border: none;
          background: black;
        "
      />
      <hr
        style="
          height: 2px;
          margin: 0;
          padding: 0;
          border: none;
          background: black;
        "
      />
  
      <div class="mt-5 flex items-center justify-between text-sm">
        <span>Ref: ${data?.referenceNo}</span>
        <span class="bold" style="font-size: 16px">THROUGH ${
          data?.modeOfDispatch
        }</span>
        <span>Dated: ${data?.noticeDate}</span>
      </div>
  
      <div class="w-50">
        <span>${data?.noticeDate}</span><br />
        <span>To,</span>
        <div style="border: 1px solid black; padding: 5px">
          <h3>${data?.custName || data?.customerName}</h3>
          <span class="bold">${data?.customerAddress} Mob No. ${
    data?.custMobileNo
  }</span>
        </div>
      </div>
  
      <span class="mt-5 block"
        ><span class="bold">Subject: DEMAND NOTICE</span>
      </span>
  
      <span style="margin-top: 15px; display: block"> Dear Sir/Madam </span>
      <span
        >Present notice is being served upon you under instruction and on behalf
        of our client HDFC Bank Ltd., having its Office at Plot Number 31,
        Najafgarh Industrial Area, Tower “A”, 1st Floor, Shivaji Marg, Moti Nagar
        New Delhi-110015 and one of its branch at Model Town, Rohtak the contents
        whereof you may be pleased to take note of:-
      </span>
  
      <div class="mt-5 flex flex-col gap-10">
        <div class="flex gap-5">
          <span>1. </span>
          <span
            >That you had applied for a credit card facility and upon your request
            Credit Card Account No <span class="bold">${
              data?.maskCard
            }</span> was
            issued to you / generated by our client. (AAN No. [Alternate Account
            Number] <span class="bold">${data?.aanNo}</span>)
          </span>
        </div>
        <div class="flex gap-5">
          <span>2. </span>
          <div class="w-full">
            <span
              >That you had been negotiating the said credit card in the markets
              at the expense of our client without updating the account. Our
              client had been regularly reminding you to update the account but in
              vain.
            </span>
          </div>
        </div>
        <div class="flex gap-5">
          <span>3. </span>
          <span
            >That in consequence thereof, as on date
            <span class="bold">${data?.noticeDate}</span>, a sum of
            <span class="bold">Rs. ${
              data?.noticeBalance
            }/-</span> stands debited in
            your credit card Account No. <span class="bold">${
              data?.maskCard
            }</span>.
            Our client has also withdrawn the said credit card facility extended
            to you and has also invalidated the said card for further usages,
            crystallized liability as on
            <span class="bold">${data?.noticeDate}</span> includes incidence of
            interest @18% from the date of charge off i.e. on the amount due
  
            <br />
            Through the present notice you are hereby called upon to pay a sum of
            <span class="bold">Rs. ${data?.noticeDate}/</span>- liability as on
            <span class="bold">${data?.noticeDate}</span>, with future interest
            @18% pa till realization of the same, else our client shall be
            constrained to initiate legal proceedings (Civil and Criminal) for the
            recovery of same under professional advise at your costs and
            consequences. That you may ignore the present notice at your own risk
            and peril.
            <br />
            <span class="bold"
              >In case of any clarification please contact Mr./ Ms.
              ${data?.clmName}-${data?.clmNo}.</span
            >
          </span>
        </div>
      </div>
  
      <span class="bold"
        >"Note: In compliance to data security standards the credit card no. is
        being masked and full alternate account number has been used in this
        notice."</span
      >
      <br /><br />
  
      <div class="flex flex-col mt-5">
        <span class="leading-normal"> Yours faithfully, </span>
        <div>
          <img src="https://i.ibb.co/cYbyzvm/sing.jpg" alt="sign" />
        </div>
        <span>(Arun Kumar Advocate)</span>
      </div>
    </body>
  </html>
  `;
